name: Build Shakzz TV Plugin

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 $GITHUB_WORKSPACE/builds/*.jar || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Write local.properties
        run: |
          cd $GITHUB_WORKSPACE/src/ShakzzTV
          echo "TMDB_API=${{ secrets.TMDB_API }}" >> local.properties
          # Add more secrets if needed here

      - name: Build Shakzz TV Plugin
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x ./gradlew
          ./gradlew :ShakzzTV:make :ShakzzTV:makePluginsJson :ShakzzTV:ensureJarCompatibility

      - name: Copy built files
        run: |
          find $GITHUB_WORKSPACE/src/ShakzzTV/build -type f -name "*.cs3" -exec cp {} $GITHUB_WORKSPACE/builds \;
          find $GITHUB_WORKSPACE/src/ShakzzTV/build -type f -name "*.jar" -exec cp {} $GITHUB_WORKSPACE/builds \;
          cp $GITHUB_WORKSPACE/src/ShakzzTV/build/plugins.json $GITHUB_WORKSPACE/builds || true

      - name: Push to builds branch
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
